name: koano
services:
  postgres:
    container_name: koano-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    platform: linux/arm64
    environment:
      POSTGRES_DB: $PG_DATABASE
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - postgres:/var/lib/postgres

  adminer:
    container_name: koano-adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "9090:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=dracula
    depends_on:
      - postgres

  # koano-api:
  #   container_name: koano-api
  #   image: koano-api:dev
  #   build:
  #     context: ../
  #     dockerfile: deployments/Dockerfile
  #   restart: unless-stopped
  #   platform: linux/arm64
  #   environment:
  #     PG_URL: "postgres:5432"
  #   env_file:
  #     - ../.env
  #   ports:
  #     - "8080:8080"
  #   expose:
  #     - "8080"

volumes:
  postgres: {}
